version: '3'

services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:134.65.245.130"

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
